name: Ajustar Revisores

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
      - review_requested
      - review_request_removed
      - assigned
      - unassigned
jobs:  
  Pull-request-action:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
    
    - name: Limpar Revisores
      run: |
           
            response=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers")   
            
            if [[ $? -eq 0 && $(echo "$response" | jq -e '.message') == "null" ]]; then
              team_reviewers=$(echo "$response" | jq -r '.teams[].slug' || echo "[]")
              reviewers=$(echo "$response" | jq -r '.users[].login' || echo "[]")

            # Cria um array para cada variável de saída
            team_reviewers_array=($team_reviewers)
            reviewers_array=($reviewers)

            fi  
              payload='{"reviewers":['
              first=true
              for reviewer in $reviewers; do
                if [ "$first" = true ]; then
                  first=false
                else
                  payload+=','
                fi
                payload+="\"$reviewer\""
              done

              payload+='],"team_reviewers":['
              first=true
              for team_reviewer in $team_reviewers; do
                if [ "$first" = true ]; then
                  first=false
                else
                  payload+=','
                fi
                payload+="\"raizen-it/$team_reviewer\""
              done
              payload+=']}'

               echo "PAYLOAD: $payload"
          
              if [ -n "$payload" ]; then
                curl -X DELETE \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer $GITHUB_TOKEN" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  -d "$payload" \
                  "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers"
          
                echo "Revisores e revisores de equipe removidos com sucesso"
              else
                echo "Nenhum revisor ou revisor de equipe a ser removido"
              fi
