name: Origem PR Main Check

on:
  pull_request:
    branches:
      - "main"
    types:
      - opened
      - reopened
jobs:
  merge-check:
    runs-on: ubuntu-latest

    steps:  
      - name: Check branch name pattern
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" =~ ^release/.* || "${{ github.event.pull_request.head.ref }}" =~ ^hotfix/.* ]]; then
            echo "Branch é uma release/ ou hotfix/ PR permitido!"
          else
            echo "Erro: Branch NÃO é uma release/ ou hotfix/ PR NÃO permitido!" && exit 1
          fi
